version: '2'
services:
  machine:
    image: ${MACHINE_IMAGE}
    network_mode: "bridge"
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.hostname_override: container_name
      io.rancher.sidekicks: application-maven-data, application-git-data, application-docker-data
    environment:
      TZ: ${TIMEZONE}
      INSECURE_REGISTRIES: '${INSECURE_REGISTRIES}'
    ports:
    - "${PORT}:22"
    privileged: true
    command: '--storage-driver=overlay'
    volumes:
      - /usr/local/bin/automation:/usr/local/bin/automation
      - /var/jenkins_home:/var/jenkins_home
