  application-${DESCRIPTION}-data:
    image: ${IMAGE_NAME}
    labels:
        io.rancher.container.pull_image: always
        io.rancher.container.hostname_override: container_name
        io.rancher.container.start_once: true
    network_mode: "none"
    volumes:
      - data-${DESCRIPTION}-${PORT}:${MOUNT_POINT}